version: "2"
services:
  server:
    image: parvparikh/roomup_backend
    container_name: roomup_backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/roomup
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  client:
    image: parvparikh/roomup_frontend
    container_name: roomup_frontend
    restart: always
    # stdin_open: true
    ports:
      - "3000:3000"
    # volumes:
    #   - ./client:/usr/src/app
  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
