version: "2"
services:
  server:
    image: <backend-docker-image-name>
    container_name: <backend-container-name>
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/your_database_name
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: your_root_password
    depends_on:
      - mysql

  client:
    image: <frontend-docker-image-name>
    container_name: <frontend-container-name>
    restart: always
    # stdin_open: true
    ports:
      - "3000:3000"
    # volumes:
    #   - ./client:/usr/src/app
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root