version: '3'
services:
  spe-mysql-container:
    image: mysql
    container_name: spe-mysql-container
    restart: always
    networks:
      - spe-network
    environment:
      MYSQL_DATABASE: "roomup"
      MYSQL_ROOT_PASSWORD: "root"
      
    ports:
      - "3307:3306"

  spe-backend-container:
    image: "parvparikh/roomup_backend"
    container_name: spe-backend-container
    restart: always
    networks:
      - spe-network
    ports:
      - "8081:8081"
    depends_on:
      - spe-mysql-container

  spe-frontend-container:
    image: "parvparikh/roomup_frontend"
    container_name: spe-frontend-container
    restart: always
    networks:
      - spe-network
    ports:
      - "3000:3000"
    depends_on:
      - spe-backend-container

networks:
  spe-network:
    driver: bridge
